#!/bin/bash

JAVA_HOME=/usr/local/jvm/openjdk-1.8.0-internal-debug
JAVA_EXE="$JAVA_HOME/bin/java"

mdir=`dirname $0`
source $mdir/ng2c-include

# TODO - break JNI_CreateJavaVM
gdb --args $JAVA_EXE $JVM_OPTS $*
